// ============================================
// VERTEX AI IMAGE GENERATION ENDPOINT
// API REST directa - no requiere SDK de GCP
// ============================================

interface VertexImageRequest {
  model: string;
  prompt: string;
  aspectRatio: string;
  imageSize: string;
  seed: number;
  location: string;
  projectId: string;
}

interface HandlerResponse {
  statusCode: number;
  body: string;
}

const handler = async (event: any, _context: any): Promise<HandlerResponse> => {
  // Solo permitir POST
  if (event.httpMethod !== "POST") {
    return {
      statusCode: 405,
      body: JSON.stringify({ error: "Method not allowed" }),
    };
  }

  // Verificar headers
  const contentType = event.headers["content-type"];
  if (!contentType?.includes("application/json")) {
    return {
      statusCode: 400,
      body: JSON.stringify({ error: "Content-Type must be application/json" }),
    };
  }

  try {
    const body: VertexImageRequest = JSON.parse(event.body || "{}");
    
    const { model, prompt, aspectRatio, imageSize, seed, location, projectId } = body;
    
    if (!model || !prompt) {
      return {
        statusCode: 400,
        body: JSON.stringify({ error: "Missing required fields: model, prompt" }),
      };
    }

    console.log(`🎯 [VertexAI Function] Generando imagen con modelo: ${model}`);
    console.log(`📝 Prompt length: ${prompt.length} chars`);
    console.log(`📐 Aspect Ratio: ${aspectRatio}`);
    console.log(`🖼️ Image Size: ${imageSize}`);

    // ============================================
    // VERTEX AI API REST
    // ============================================
    
    // Obtener token de acceso de GCP
    const accessToken = await getGCPAccessToken();
    
    if (!accessToken) {
      console.warn('⚠️ No se pudo obtener token de GCP, usando fallback a Gemini API');
      return await generateWithGeminiAPI(model, prompt, aspectRatio, imageSize, seed);
    }

    const gcpProjectId = projectId || process.env.GCP_PROJECT_ID || 'estudio-56-prod';
    const gcpLocation = location || 'us-central1';

    // Convertir aspectRatio al formato de Vertex AI
    const aspectRatioMap: Record<string, { width: number; height: number }> = {
      '1:1': { width: 1024, height: 1024 },
      '9:16': { width: 768, height: 1024 },
      '16:9': { width: 1024, height: 576 },
      '4:5': { width: 832, height: 1024 },
      '3:4': { width: 768, height: 1024 },
    };
    
    const { width, height } = aspectRatioMap[aspectRatio] || { width: 1024, height: 1024 };

    // Construir URL de Vertex AI
    const vertexUrl = `https://${gcpLocation}-aiplatform.googleapis.com/v1/projects/${gcpProjectId}/locations/${gcpLocation}/publishers/google/models/${model}:predict`;
    
    console.log(`📡 Enviando solicitud a Vertex AI: ${vertexUrl}`);

    // Hacer request a Vertex AI
    const vertexResponse = await fetch(vertexUrl, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        instances: [{ prompt }],
        parameters: {
          sampleCount: 1,
          seed: seed,
          imageSize: {
            width,
            height,
          },
        },
      }),
    });

    if (!vertexResponse.ok) {
      const errorData = await vertexResponse.json();
      console.error('❌ Vertex AI error:', errorData);
      
      // Si Vertex AI falla, intentar con Gemini API
      console.warn('⚠️ Vertex AI falló, usando fallback a Gemini API');
      return await generateWithGeminiAPI(model, prompt, aspectRatio, imageSize, seed);
    }

    const vertexData = await vertexResponse.json();
    console.log(`✅ Vertex AI response received`);

    // Procesar respuesta de Vertex AI
    if (vertexData.predictions && vertexData.predictions.length > 0) {
      const prediction = vertexData.predictions[0];
      
      if (prediction.bytesBase64Encoded) {
        const imageUrl = `data:image/jpeg;base64,${prediction.bytesBase64Encoded}`;
        
        return {
          statusCode: 200,
          body: JSON.stringify({
            success: true,
            imageUrl,
            model,
            seed,
          }),
        };
      }
    }

    throw new Error("No image generated by Vertex AI");

  } catch (error: any) {
    console.error('❌ [VertexAI Function] Error:', error.message);
    console.error('📝 Stack trace:', error.stack);
    
    // Intentar fallback a Gemini API
    console.warn('⚠️ Error en Vertex AI, intentando fallback a Gemini API');
    
    try {
      const body: VertexImageRequest = JSON.parse(event.body || "{}");
      return await generateWithGeminiAPI(body.model, body.prompt, body.aspectRatio, body.imageSize, body.seed);
    } catch (fallbackError: any) {
      return {
        statusCode: 500,
        body: JSON.stringify({
          error: error.message || "Internal server error",
          message: "Error generating image with Vertex AI and Gemini fallback also failed",
        }),
      };
    }
  }
};

// ============================================
// OBTENER TOKEN DE ACCESO DE GCP
// ============================================
async function getGCPAccessToken(): Promise<string | null> {
  try {
    // Método 1: Usar GOOGLE_APPLICATION_CREDENTIALS si está disponible
    const credentialsJson = process.env.GOOGLE_APPLICATION_CREDENTIALS;
    
    if (credentialsJson) {
      console.log('📄 GOOGLE_APPLICATION_CREDENTIALS encontrado');
      
      try {
        const credentials = JSON.parse(credentialsJson);
        
        // Generar token JWT y intercambiar por access token
        const token = await generateJWTToken(credentials);
        
        if (token) {
          const response = await fetch('https://oauth2.googleapis.com/token', {
            method: 'POST',
            headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
            body: new URLSearchParams({
              grant_type: 'urn:ietf:params:oauth:grant-type:jwt-bearer',
              assertion: token,
            }),
          });
          
          const data = await response.json();
          return data.access_token || null;
        }
      } catch (parseError) {
        console.warn('⚠️ Error parseando GOOGLE_APPLICATION_CREDENTIALS');
      }
    }

    // Método 2: Si estamos en GCP, usar metadata service
    if (process.env.GOOGLE_CLOUD_PROJECT) {
      try {
        const response = await fetch(
          'http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token',
          {
            headers: { 'Metadata-Flavor': 'Google' },
          }
        );
        const data = await response.json();
        return data.access_token || null;
      } catch (metadataError) {
        console.warn('⚠️ Error accediendo a metadata service');
      }
    }

    return null;
  } catch (error: any) {
    console.warn('⚠️ Error obteniendo token de GCP:', error.message);
    return null;
  }
}

// ============================================
// GENERAR JWT PARA AUTENTICACIÓN DE GCP
// ============================================
async function generateJWTToken(credentials: any): Promise<string | null> {
  try {
    const header = {
      alg: 'RS256',
      typ: 'JWT',
    };

    const now = Math.floor(Date.now() / 1000);
    const payload = {
      iss: credentials.client_email,
      sub: credentials.client_email,
      aud: 'https://oauth2.googleapis.com/token',
      iat: now,
      exp: now + 3600,
      scope: 'https://www.googleapis.com/auth/cloud-platform',
    };

    // Codificar header y payload
    const encodedHeader = btoa(JSON.stringify(header)).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
    const encodedPayload = btoa(JSON.stringify(payload)).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');

    // Firmar con clave privada
    const crypto = require('crypto');
    const signature = crypto
      .createSign('RSA-SHA256')
      .update(`${encodedHeader}.${encodedPayload}`)
      .sign(credentials.private_key, 'base64')
      .replace(/\+/g, '-')
      .replace(/\//g, '_')
      .replace(/=+$/, '');

    return `${encodedHeader}.${encodedPayload}.${signature}`;
  } catch (error: any) {
    console.warn('⚠️ Error generando JWT:', error.message);
    return null;
  }
}

// ============================================
// FALLBACK: GEMINI API DIRECTO
// ============================================
async function generateWithGeminiAPI(
  model: string,
  prompt: string,
  aspectRatio: string,
  imageSize: string,
  seed: number
): Promise<HandlerResponse> {
  console.log(`🔄 [VertexAI Function] Usando Gemini API como fallback`);
  
  const apiKey = process.env.GEMINI_API_KEY || process.env.VITE_GEMINI_API_KEY;
  
  if (!apiKey) {
    return {
      statusCode: 500,
      body: JSON.stringify({
        error: "No API key available",
        message: "Neither Vertex AI nor Gemini API keys are configured",
      }),
    };
  }

  // Mapear modelo de imagen a modelo de Gemini
  let geminiModel = 'gemini-2.5-flash-image';
  if (model.includes('imagen-3.0-pro')) {
    geminiModel = 'gemini-3.0-pro-image-exp';
  }

  // Convertir aspectRatio
  const aspectRatioMap: Record<string, string> = {
    '1:1': '1:1',
    '9:16': '9:16',
    '16:9': '16:9',
    '4:5': '4:5',
    '3:4': '3:4',
  };
  
  const finalAspectRatio = aspectRatioMap[aspectRatio] || '1:1';

  const url = `https://generativelanguage.googleapis.com/v1beta/models/${geminiModel}:generateContent?key=${apiKey}`;
  
  const requestBody = {
    contents: [{
      parts: [{ text: prompt }]
    }],
    config: {
      imageConfig: {
        aspectRatio: finalAspectRatio,
      }
    }
  };

  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(requestBody),
    });

    if (!response.ok) {
      const errorData = await response.json();
      console.error('❌ Gemini API error:', errorData);
      throw new Error(errorData.error?.message || `Gemini API error: ${response.status}`);
    }

    const data = await response.json();
    
    if (data.candidates && data.candidates.length > 0) {
      const parts = data.candidates[0].content?.parts;
      
      if (parts && parts.length > 0) {
        for (const part of parts) {
          if (part.inlineData && part.inlineData.data) {
            const imageUrl = `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
            
            return {
              statusCode: 200,
              body: JSON.stringify({
                success: true,
                imageUrl,
                model: geminiModel,
                seed,
                fallback: true,
              }),
            };
          }
        }
      }
    }

    throw new Error("No image in Gemini response");

  } catch (error: any) {
    console.error('❌ Gemini fallback error:', error.message);
    return {
      statusCode: 500,
      body: JSON.stringify({
        error: error.message || "Fallback generation failed",
        message: "Both Vertex AI and Gemini API failed",
      }),
    };
  }
}

export { handler };