# Build stage
FROM node:20-alpine AS builder
WORKDIR /app

# Accept build arguments from Easypanel
ARG VITE_GEMINI_API_KEY
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG REACT_APP_SUPABASE_URL
ARG REACT_APP_USE_VIDEO_WORKER
ARG REACT_APP_VIDEO_WORKER_URL
ARG VITE_GOOGLE_VERTEX_PROJECT
ARG VITE_GOOGLE_VERTEX_LOCATION
ARG FAL_AI_API_KEY
ARG MERCADOPAGO_PUBLIC_KEY

# Copy package files and install dependencies
COPY package*.json ./
RUN npm ci --verbose

# Copy source code
COPY . .

# Create .env file with build arguments for Vite build
RUN cat > .env << EOF
VITE_GEMINI_API_KEY=${VITE_GEMINI_API_KEY}
VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
REACT_APP_SUPABASE_URL=${REACT_APP_SUPABASE_URL}
REACT_APP_USE_VIDEO_WORKER=${REACT_APP_USE_VIDEO_WORKER}
REACT_APP_VIDEO_WORKER_URL=${REACT_APP_VIDEO_WORKER_URL}
VITE_GOOGLE_VERTEX_PROJECT=${VITE_GOOGLE_VERTEX_PROJECT}
VITE_GOOGLE_VERTEX_LOCATION=${VITE_GOOGLE_VERTEX_LOCATION}
FAL_AI_API_KEY=${FAL_AI_API_KEY}
MERCADOPAGO_PUBLIC_KEY=${MERCADOPAGO_PUBLIC_KEY}
EOF

# Verify .env file was created
RUN echo "✅ Build .env configurado" && cat .env

# Build the application with production mode
RUN npm run build || (echo "❌ Build failed" && exit 1)

# Verify build output
RUN if [ -d dist ]; then ls -la dist/ && echo "✅ Build completado"; else echo "❌ dist/ no existe" && exit 1; fi

# Production stage
FROM node:20-alpine
WORKDIR /app

# Accept runtime arguments from Easypanel
ARG NODE_ENV
ARG PORT
ARG VITE_GEMINI_API_KEY
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG REACT_APP_SUPABASE_URL
ARG REACT_APP_USE_VIDEO_WORKER
ARG REACT_APP_VIDEO_WORKER_URL
ARG VITE_GOOGLE_VERTEX_PROJECT
ARG VITE_GOOGLE_VERTEX_LOCATION
ARG FAL_AI_API_KEY
ARG GEMINI_API_KEY
ARG GOOGLE_VERTEX_PROJECT
ARG GOOGLE_VERTEX_LOCATION
ARG MERCADOPAGO_ACCESS_TOKEN
ARG MERCADOPAGO_PUBLIC_KEY
ARG SUPABASE_SERVICE_ROLE_KEY
ARG SECRETS_SCAN_SMART_DETECTION_ENABLED

# Copy package files
COPY package*.json ./

# Install only production dependencies
RUN npm ci --only=production

# Copy built frontend from builder
COPY --from=builder /app/dist ./dist

# Copy server files
COPY server ./server
COPY server.js .

# Create .env for runtime with all variables
RUN cat > .env << 'EOF'
NODE_ENV=${NODE_ENV:-production}
PORT=${PORT:-3000}
VITE_GEMINI_API_KEY=${VITE_GEMINI_API_KEY}
VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
REACT_APP_SUPABASE_URL=${REACT_APP_SUPABASE_URL}
REACT_APP_USE_VIDEO_WORKER=${REACT_APP_USE_VIDEO_WORKER}
REACT_APP_VIDEO_WORKER_URL=${REACT_APP_VIDEO_WORKER_URL}
VITE_GOOGLE_VERTEX_PROJECT=${VITE_GOOGLE_VERTEX_PROJECT}
VITE_GOOGLE_VERTEX_LOCATION=${VITE_GOOGLE_VERTEX_LOCATION}
FAL_AI_API_KEY=${FAL_AI_API_KEY}
GEMINI_API_KEY=${GEMINI_API_KEY}
GOOGLE_VERTEX_PROJECT=${GOOGLE_VERTEX_PROJECT}
GOOGLE_VERTEX_LOCATION=${GOOGLE_VERTEX_LOCATION}
MERCADOPAGO_ACCESS_TOKEN=${MERCADOPAGO_ACCESS_TOKEN}
MERCADOPAGO_PUBLIC_KEY=${MERCADOPAGO_PUBLIC_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
SECRETS_SCAN_SMART_DETECTION_ENABLED=${SECRETS_SCAN_SMART_DETECTION_ENABLED}
EOF

EXPOSE 3000

CMD ["node", "server.js"]
