[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  # Configuración global para todas las funciones
  timeout = 26

[functions."generate-image"]
  # Configuración específica para tu función de imagen
  node_bundle = true
  external_node_modules = ["google-auth-library"]

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "credentialless"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true