[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  # Dejamos este bloque vacío o con configuraciones globales de empaquetado
  node_bundle = true

[functions."generate-image"]
  # Aquí es donde el plan Pro busca el tiempo extendido
  timeout = 26
  external_node_modules = ["google-auth-library"]

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "credentialless"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true